# Generated by Django 5.1.1 on 2024-09-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovozmodel',
            name='saylovchi',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
